version: '2'
services:
    myfamilytree-app:
        image: myfamilytree
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://myfamilytree-mysql:3306/myfamilytree?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=myfamilytree-elasticsearch:9300
        ports:
            - 8080:8080
    myfamilytree-mysql:
        extends:
            file: mysql.yml
            service: myfamilytree-mysql
    myfamilytree-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: myfamilytree-elasticsearch
